<?php /** @var $this \Ctrl\View\PhpView */ ; ?>

<?php echo $this->pageTitle('Users'); ?>

<table class="table">
    <thead>
    <tr>
        <th>id</th>
        <th>username</th>
        <th>actions</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->users as $user): ?>
        <tr>
            <td><?php echo $user->getId(); ?></td>
            <td><?php echo $user->getUsername(); ?></td>
            <td>
                <?php echo $this->ctrlButton('link', array(
                    'url' => $this->url('ctrl_auth/id', array(
                        'controller' => 'user',
                        'action' => 'edit',
                        'id' => $user->getId(),
                    )),
                    'value' => 'edit',
                )); ?>
                <?php echo $this->ctrlButton('link', array(
                'url' => $this->url('ctrl_auth/id', array(
                    'controller' => 'permission',
                    'action' => 'index',
                    'id' => $user->getId(),
                )),
                'value' => 'permissions',
                ), 'info'); ?>
                <?php echo $this->ctrlButton('link', array(
                'url' => $this->url('ctrl_auth/id', array(
                    'controller' => 'user',
                    'action' => 'delete',
                    'id' => $user->getId(),
                )),
                'value' => 'delete',
                'confirm' => 'are you sure you want to delete this user?',
                ), 'danger'); ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>