<?php
/** @var $this \Ctrl\View\PhpView */
echo $this->pageTitle($user->getUsername(), 'edit user');

$form->setLabel('Please provide your credentials');
echo $this->ctrlForm()->createForm(
    $form,
    array(
        $this->ctrlButton('submit', array('value' => 'save'), 'primary'),
        $this->ctrlButton('link', array(
            'value' => 'cancel',
            'url' => $form->getReturnUrl(),
        )),
    )
);