<?php /** @var $this \Ctrl\View\PhpView */ ; ?>
<?php /** @var $users \CtrlAuth\Domain\User[] */ ; ?>

<?php echo $this->pageTitle('Users'); ?>

<?php echo $this->buttonBar(array(
    $this->buttonGroup(array(
        $this->ctrlButton('link', array(
            'url' => $this->url('ctrl_auth', array(
                'controller' => 'user',
                'action' => 'add',
            )),
            'value' => 'add user',
        ), 'primary'),
        $this->ctrlButton('link', array(
            'url' => $this->url('ctrl_auth', array(
                'controller' => 'role',
            )),
            'value' => 'view roles',
        )),
    ), array('pull-right' => true))
)); ?>

<table class="table">
    <thead>
    <tr>
        <th>id</th>
        <th>username</th>
        <th>system role</th>
        <th>actions</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($users as $user): ?>
        <tr>
            <td><?php echo $user->getId(); ?></td>
            <td><?php echo $user->getUsername(); ?></td>
            <td><?php if ($user->isSystemUser()) : ?><span class="label label-info">yes</span><?php endif; ?></td>
            <td>
                <?php echo $this->ctrlButton('link', array(
                    'url' => $this->url('ctrl_auth/id', array(
                        'controller' => 'user',
                        'action' => 'edit',
                        'id' => $user->getId(),
                    )),
                    'value' => 'edit',
                )); ?>
                <?php echo $this->ctrlButton('link', array(
                'url' => $this->url('ctrl_auth/id', array(
                    'controller' => 'role',
                    'action' => 'index',
                    'id' => $user->getId(),
                )),
                'value' => 'roles',
                ), 'info'); ?>
                <? if (!$user->getPassword()): ?>
                    <?php echo $this->ctrlButton('link', array(
                    'url' => $this->url('ctrl_auth/id', array(
                        'controller' => 'user',
                        'action' => 'delete',
                        'id' => $user->getId(),
                    )),
                    'value' => 'delete',
                    'confirm' => 'are you sure you want to delete this user?',
                    ), 'danger'); ?>
                <? endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>