<?php
/** @var $this \Ctrl\View\PhpView */
$form->setLabel('Change the role name');
echo $this->ctrlForm()->createForm(
    $form,
    array(
        $this->ctrlButton('submit', array('value' => 'save'), 'primary'),
        $this->ctrlButton('link', array(
            'value' => 'cancel',
            'url' => $this->url('ctrl_auth/default', array(
                'controller' => 'role',
            )),
        )),
    )
);