<?php /** @var $this \Ctrl\View\PhpView */ ; ?>
<?php /** @var $roles \CtrlAuth\Domain\Role[] */ ; ?>

<?php $subtitle = ($user) ? 'for user '.$user->getUsername() : ''; ?>
<?php echo $this->pageTitle('Roles', $subtitle); ?>

<?php
$buttons = array();
if ($user) {
    $buttons[] = $this->ctrlButton('link', array(
        'url' => $this->url('ctrl_auth/default/id', array(
            'controller' => 'user',
            'action' => 'add-role',
            'id' => $user->getId(),
        )),
        'value' => 'add role for user',
    ), 'grant');
    $buttons[] = $this->ctrlButton('link', array(
        'url' => $this->url('ctrl_auth/default', array(
            'controller' => 'role',
        )),
        'value' => 'show all roles',
    ));
}
$buttons[] = $this->ctrlButton('link', array(
    'url' => $this->url('ctrl_auth/default', array(
        'controller' => 'user',
        'action' => 'index',
    )),
    'value' => 'view users',
));

echo $this->buttonBar(array(
    $this->buttonGroup($buttons, array('pull-right' => true))
)); ?>

<table class="table">
    <thead>
    <tr>
        <th>name</th>
        <th>system role</th>
        <th>move</th>
        <th>actions</th>
    </tr>
    </thead>
    <tbody>
    <?php

    $view = $this;
    /** @var $role \CtrlAuth\Domain\Role */
    $getButtons = function ($role) use ($user, $view, $canEditRoles, $canEditSystemRoles) {
        $buttons = array();
        $buttons[] = $view->ctrlButton('link', array(
            'url' => $view->url('ctrl_auth/default/id', array(
                'controller' => 'permission',
                'action' => 'index',
                'id' => $role->getId(),
            )),
            'value' => 'permissions',
        ), 'info');
        if ($user) {
            $buttons[] = $view->ctrlButton('link', array(
                'url' => $view->url('ctrl_auth/default/id/query', array(
                    'controller' => 'user',
                    'action' => 'remove-role',
                    'id' => $user->getId(),
                    'role' => $role->getId(),
                )),
                'value' => 'unlink',
                'confirm' => 'are you sure you want to unlink role?',
            ), 'warning');
        }
        if ($canEditRoles) {
            if (!$role->isSystemRole() || $canEditSystemRoles) {
                $buttons[] = $view->ctrlButton('link', array(
                    'url' => $view->url('ctrl_auth/role_edit', array(
                        'role' => $role->getId(),
                    )),
                    'value' => 'edit',
                ));
            }
        }
        return implode(PHP_EOL, $buttons);
    };
    $generateRows = function ($roles, $depth = 0, $current = null) use (&$generateRows, $getButtons, $view) {
        $nextDepth = $depth+1;
        $firstInDepth = true;
        $countInDepth = ($depth) ? count($roles) : 0;
        $singleChild = $firstInDepth && $countInDepth <= 1;
        foreach ($roles as $role):
            $countInDepth--;
            if ($current == null && count($role->getChildren())) continue;
            if ($current != null && $current->getRoleId() == $role->getRoleId()) return; ?>
            <tr>
                <?php if ($depth): ?>
                <td class="no-border"><span class="tree-spacer"><?php if ($depth) echo '|'.implode('', array_fill(0, $depth, '____')).' '; ?></span><?php echo $role->getName(); ?></td>
                <?php else : ?>
                <td><?php echo $role->getName(); ?></td>
                <?php endif; ?>
                <td><?php if ($role->isSystemRole()) : ?><span class="label label-info">yes</span><?php endif; ?></td>
                <td>
                    <?php
                        if ($depth && !$singleChild) {
                            $buttons = array();
                            if ($countInDepth > 0) $buttons[] = $view->ctrlButton('link', array('value' => '<i class="icon-chevron-down"></i>', 'url' => $view->url('ctrl_auth/default/id/query', array(
                                'controller' => 'role',
                                'action' => 'move-parent',
                                'id' => $current->getId(),
                                'parent' => $role->getId(),
                                'direction' => 'up',
                            ))));
                            else $buttons[] = $view->ctrlButton('link', array('value' => '<i class="icon-minus"></i>', 'url' => '#'));
                            if (!$firstInDepth > 0) $buttons[] = $view->ctrlButton('link', array('value' => '<i class="icon-chevron-up"></i>', 'url' => $view->url('ctrl_auth/default/id/query', array(
                                'controller' => 'role',
                                'action' => 'move-parent',
                                'id' => $current->getId(),
                                'parent' => $role->getId(),
                                'direction' => 'down',
                            ))));
                            else $buttons[] = $view->ctrlButton('link', array('value' => '<i class="icon-minus"></i>', 'url' => '#'));
                            echo $view->buttonGroup($buttons);
                        }
                    ?>
                </td>
                <td>
                    <?php echo $getButtons($role) ?>
                </td>
            </tr>
            <?php $firstInDepth = false; ?>
            <?php $generateRows($role->getParents(), $nextDepth, $role); ?>

        <?php endforeach;
    };
    $generateRows($roles);
    ?>
    </tbody>
</table>