<?php
/** @var $this \Ctrl\View\PhpView */
echo $this->pageTitle('Remove this role', 'Are you sure?');
echo $this->ctrlFormActions(array(
        $this->ctrlButton('link', array(
            'value' => 'remove',
            'url' => $this->url('ctrl_auth/role_edit/query', array(
                'role' => $role->getId(),
                'slug' => 'remove',
                'remove-do' => '1',
            ))
        ), 'danger'),
        $this->ctrlButton('link', array(
            'value' => 'cancel',
            'url' => $this->url('ctrl_auth/default', array(
                'controller' => 'role',
            )),
        )),
    )
);