<?php /** @var $this \Ctrl\View\PhpView */ ?>
<?php /** @var $auth \Ctrl\Permissions\Acl */ ?>
<?php /** @var $role \CtrlAuth\Domain\Role */ ?>
<?php echo $this->pageTitle($role->getName(), 'Permissions'); ?>

<?php
$parentsButtons = array();
if (count($role->getParentMaps())){
    echo '<h5>Child roles</h5>';
    foreach ($role->getParents() as $p) {
        $parentsButtons[] = $this->ctrlButton('link', array('value' => $p->getName(), 'url' => $this->url('ctrl_auth/default/id', array(
            'controller' => 'permission',
            'id' => $p->getId(),
        ))));
    }
}
echo $this->buttonBar(array(
        $this->buttonGroup($parentsButtons),
        $this->buttonGroup(array(
            $this->ctrlButton('link', array('value' => 'view roles', 'url' => $this->url('ctrl_auth/default', array(
                'controller' => 'role',
            ))))
        ), array('pull-right' => true)),
    )
);
?>
<table class="table">
    <thead>
    <tr>
        <th>permissions</th>
        <th>current value</th>
        <th>parent value</th>
        <th>actions</th>
    </tr>
    </thead>
    <tbody>

    <?php
    $view = $this;
    $generateRows = function ($tree, $depth = 0, $parents = array()) use (&$generateRows, $auth, $role, $view) {
        /** @var $role \CtrlAuth\Domain\Role */
        $nextDepth = $depth+1;
        foreach ($tree as $current => $children):
            $path = $parents;
            $path[] = $current;
            $resourceName = $auth->getResourceNameFromPath($path);
            $state = (!$role->hasPermissionForResource($resourceName)) ? 'inherit' : (
                ($auth->isAllowed($role, $resourceName)) ? 'allow' : 'deny'
            );
            $parent = '*';
            $inheritedState = $state;
            if ($state == 'inherit') {
                $inheritedState = ($auth->isAllowed($role, $resourceName)) ? 'allow' : 'deny';
                if ($auth->isAllowed($role, $resourceName)) {
                    foreach ($role->getParents() as $p) {
                        if ($auth->isAllowed($p, $resourceName)) {
                            $parent = $p->getName();
                            break;
                        }
                    }
                    if ($parent == '*') {
                        $parent = '_self_';
                    }
                }
                if (!$auth->isAllowed($role, $resourceName)) {
                    foreach ($role->getParents() as $p) {
                        if ($p->hasPermissionForResource($resourceName)) {
                            $parent = $p->getName();
                            break;
                        }
                    }
                    if ($parent == '*') {
                        $parent = '_self_';
                    }
                }
            }
            if ($parent == '_self_') {
                if (!count($parents)) {
                    $parent = '*';
                } else {
                    $parent = '&#94;';
                }
            }
            ?>
            <tr>
                <?php if (count($parents)): ?>
                    <td class="no-border"><span class="tree-spacer"><?php if ($depth) echo '|'.implode('', array_fill(0, $depth, '____')).' '; ?></span><?php echo $current; ?></td>
                <?php else : ?>
                    <td><?php echo $current; ?></td>
                <?php endif; ?>
                <td>
                    <span class="label <?php echo ($state == 'inherit') ? '' : (
                    ($state == 'allow') ? 'label-success' : 'label-important'
                ); ?>"><?php echo $state; ?></span>
                </td>
                <td>
                    <span class="label <?php echo ($inheritedState == 'allow') ? 'label-success' : 'label-important'; ?>"> <?php echo $parent; ?> </span>
                </td>
                <td>
                    <?php
                        $urlParams = array('role' => $role->getId(), 'resource' => $resourceName);
                        $allowButton = $view->ctrlButton('link', array('value' => 'allow', 'url' => $view->url('ctrl_auth/role_perm', array_merge($urlParams, array(
                            'task' => 'allow'
                        )))), 'grant');
                        $denyButton = $view->ctrlButton('link', array('value' => 'deny', 'url' => $view->url('ctrl_auth/role_perm', array_merge($urlParams, array(
                            'task' => 'deny'
                        )))), 'warning');
                        $inheritButton = $view->ctrlButton('link', array('value' => 'inherit', 'url' => $view->url('ctrl_auth/role_perm', array_merge($urlParams, array(
                            'task' => 'inherit'
                        )))));
                        if ($state == 'inherit') {
                            echo $allowButton.$denyButton;
                        } else {
                            echo $inheritButton;
                            if ($state == 'deny') {
                                echo $allowButton;
                            } else {
                                echo $denyButton;
                            }
                        }
                    ?>
                </td>
            </tr>
            <?php $generateRows($children, $nextDepth, $path); ?>
        <?php endforeach;
    };
    $generateRows($auth->getResourceTree());
    ?>
    </tbody>
</table>