<?php /** @var $auth \Ctrl\Permissions\Acl */ ?>
<?php echo $this->pageTitle('Permissionsfor role', $role->getName()); ?>

<?php
//var_dump($auth->getResourceSets());
?>

<table class="table">
    <tbody>
    <?php foreach ($auth->getResourceSets() as $set): ?>
        <tr>
            <th colspan="4"><?php echo $set; ?></th>
        </tr>
        <?php foreach ($auth->getResources() as $resource): ?>
            <?php if (strpos($resource, $set) === false) continue; ?>
            <?php $allowed = ($auth->hasResource($resource) && $auth->hasRole($role->getName()) && $auth->isAllowed($role->getName(), $resource)) ? true: false ?>
            <tr>
                <td><label class="icon icon-chevron-right"></label></td>
                <td><?php echo $resource; ?></td>
                <td><span class="label label-<?php echo ($allowed) ? 'success': 'important'; ?>"><?php echo ($allowed) ? 'allow': 'deny'; ?></span></td>
                <td>
                    <?php
                    if ($allowed) {
                        echo $this->ctrlButton('link', array(
                            'url' => $this->url('ctrl_auth/permission', array(
                                'controller' => 'permission',
                                'action' => 'deny-role',
                                'role' => $role->getId(),
                                'resource' => $resource,
                            )),
                            'value' => 'revoke',
                        ), 'info');
                    } else {
                        echo $this->ctrlButton('link', array(
                            'url' => $this->url('ctrl_auth/permission', array(
                                'controller' => 'permission',
                                'action' => 'allow-role',
                                'role' => $role->getId(),
                                'resource' => $resource,
                            )),
                            'value' => 'grant',
                        ), 'warning');
                    }
                    ?>
                </td>
            </tr>
        <?php endforeach; ?>
    <?php endforeach; ?>
    </tbody>
</table>